### ISSUE TITLE
[fix/image-upload] 일부 파일이 업로드 되지 않는 문제를 해결한다.

### ISSUE THREAD

**Issue by headF1rst** [GIFTERZ/2023-text-me#216]
## 요약

> 몇몇 이미지를 업로드하는데 실패하는 상황 발생.

## 진행 상황

- [x] 업로드 실패시 예외 메시지 추가
- [x] 몇몇 이미지 업로드시 ImageIO가 InputStream을 읽어오지 못하는 문제 해결
  - 이미지 너비가 넓은 이미지 업로드가 되지 않는 문제를 targetWidth를 줄여 해결

**Comment by headF1rst** [comment]
<img width="824" alt="스크린샷 2022-12-14 오전 3 17 55" src="https://user-images.githubusercontent.com/55884834/207413392-253115dc-fa29-4f1f-a985-5a363ad7856a.png">

`BufferedImage image = ImageIO.read(originalImage.getInputStream());` 
위의 메서드에서 `ImageIO.read()` 메서드의 결과가 null값이 나오는걸로 파악됩니다.

구글링해봤더니 많은 개발자가 겪는 문제인거 같은데...

**Comment by juy4556** [comment]
https://ij-plugins.sourceforge.net/plugins/imageio/
근데 또 위 링크 보면 plugin으로도 HEIC, HEIF은 지원을 못하는 것 같습니다.

**Comment by headF1rst** [comment]
> 해결방안으로 JDeil라는 JDK를 사용해볼까요? https://www.idrsolutions.com/jdeli/ https://support.idrsolutions.com/jdeli/

가보즈아!
