### ISSUE TITLE
[feature/add-letterWrite] 편지 쓰기 컴포넌트를 구현한다.

### ISSUE THREAD

**Issue by sseungki98** [GIFTERZ/2023-text-me#5]
### 작업 내용
- [ ] 카드 선택 
- [ ] 카드 미리보기
- [ ] 편지 쓰기
- [ ] 편지 작성 form
- [ ] 작성 완료 후 페이지

**Comment by chchaeun** [comment]
[feature/add-letter-write] 브랜치명 `/` 뒤는 스네이크 케이스로 작성해주세요!

**Comment by sseungki98** [comment]
> [feature/add-letter-write] 브랜치명 `/` 뒤는 스네이크 케이스로 작성해주세요!
> 
> 이슈가 큰 것 같아서 와이어프레임에서 나눠진 대로 이슈도 분리하면 좋을 것 같아요. 이슈가 크면 계속 닫히지 않고 남아있게 되어서 작업 시간을 예측하고 효율적으로 업무를 분담하기 어렵습니다. 많이 쪼개도 되니까 최대한 하루 안에 해결할 수 있는 범위로 이슈를 분리해주세요!

그럼 이슈를 [feature/add-select-card] 편지에 사용될 카드를 선택하는 컴포넌트를 구현한다 정도의 크기로 여러개 이슈를 띄워도 되는건가용?

**Comment by chchaeun** [comment]
네!!

**Comment by chchaeun** [comment]
스네이크 케이스가 아니라 케밥 케이스라고 하네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
>Kebab case(케밥 케이스) : test-variable-one
두 단어 이상을 합칠 때 바(대시)로 구분해준다
꼬치에 꿰인 케밥 고기 모양이라 이 이름이 붙었다
